name: pix_2_pdf
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  another_flutter_splash_screen: ^1.2.1
  pdf: ^3.11.1
  image_picker: ^1.0.0
  path_provider: ^2.1.4
  dotted_border: ^2.1.0
  another_flushbar: ^1.12.30
  open_file: 3.3.2
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true